Fix wrong orientation when there isn't at least 2 elements on the list
OutSystems/react-virtualized-list pull request #4
Opened 2018-09-10 12:16 UTC by scout719

2018-09-10 12:25 UTC, joaompneves requested changes

2018-09-10 12:25 UTC, joaompneves commented on src/react-virtualized-list/virtualized-scroll-viewer.tsx
> +            if (!Spacer.isSpacer(elem)) {
Why do you have to check very element? Its not supposed to have spacers in between

2018-09-10 12:25 UTC, joaompneves commented on src/react-virtualized-list/virtualized-scroll-viewer.tsx
>          // ignore spacer elements
if (children.length > 0) {
  ...

2018-09-10 12:25 UTC, joaompneves commented on src/react-virtualized-list/spacer.tsx
> +        return React.DOM.script({ key: childKey, style: style, data: SPACER_ATTRIBUTE });
instead of an attribute use a ref

2018-09-10 12:48 UTC, scout719 commented on src/react-virtualized-list/spacer.tsx
> +        return React.DOM.script({ key: childKey, style: style, data: SPACER_ATTRIBUTE });
I tried it but I don't know how to work with ReactFragments and so. Care to help me?

2018-09-10 12:51 UTC, oscsx requested changes
variable casing

2018-09-10 12:51 UTC, oscsx commented on src/react-virtualized-list/virtualized-scroll-viewer.tsx
> +            let start_idx = Spacer.isSpacer(children[0]) ? 1 : 0;
start_idx -> startIdx
end_idx -> endIdx

2018-09-10 13:39 UTC, joaompneves submitted a review, later dismissed

2018-09-10 13:39 UTC, joaompneves commented on src/react-virtualized-list/virtualized-scroll-viewer.tsx
> +            let start_idx = this.isSpacer(children[0]) ? 1 : 0;
startIdx
endIdx

2018-09-11 08:52 UTC, oscsx submitted a review, later dismissed

2018-09-11 10:38 UTC, oscsx approved these changes

2018-09-12 13:28 UTC, joaompneves approved these changes

2018-09-12 13:30 UTC, merged